name: Auto Tag on Main Merge

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tag
        id: get-latest-tag
        run: |
          # Get the latest tag, if no tags exist, start with v0.0.0
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Increment patch version
        id: increment-version
        run: |
          latest_tag="${{ steps.get-latest-tag.outputs.latest_tag }}"

          # Remove 'v' prefix if it exists
          version=${latest_tag#v}

          # Split version into parts
          IFS='.' read -ra VERSION_PARTS <<< "$version"
          major=${VERSION_PARTS[0]:-0}
          minor=${VERSION_PARTS[1]:-0}
          patch=${VERSION_PARTS[2]:-0}

          # Increment patch version
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"

          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          new_version="${{ steps.increment-version.outputs.new_version }}"

          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create tag
          git tag -a "$new_version" -m "Auto-generated tag $new_version"

          # Push tag
          git push origin "$new_version"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment-version.outputs.new_version }}
          release_name: Release ${{ steps.increment-version.outputs.new_version }}
          body: |
            Auto-generated release for ${{ steps.increment-version.outputs.new_version }}

            Changes in this release:
            - Automatic patch version increment
          draft: false
          prerelease: false
